spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1214choiZ!

  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

DATA:
  HOLIDAYKEY: jclfLVr8JXUFW8HoAu56wN4H/6AXiLKqAfXdSZOosnq4shwUN8iLtQfG6mhaQOStzbLgWXvxLrOZ5kzUqUQ3Vg==
